### PR TITLE
Adding Enterprise support

### PR DESCRIPTION
**Pull request by LDaneliukas**
Currently, we are able to create & attach GitHub runners in the organization and repository levels, however, there's also the enterprise level (from which orgs & repos can inherit runners).

Adding support for Enterprise level runners. Tested provisioning enterprise, organization, and repository level runners on CentOS Linux release 7.7.1908 virtual machines.

Updated README.md to reflect the code changes.

### CODE REVIEW

**Comment by LDaneliukas** [comment]
Ping.

**Review by oscarsj — APPROVED** [review]
Looks pretty good, thanks for the contribution!

**Comment by LDaneliukas** [comment]
> 
> 
> Thanks for this contribution!
> It would be perfect if you could add a couple of tests to check when `enteprise_name` is set and also when there is neither `org_name` nor `enteprise_name` that it should fail.
> 
> As an example to follow, those tests should be similar to this one:
> https://github.com/Telefonica/puppet-github-actions-runner/blob/master/spec/classes/github_actions_runner_spec.rb#L317-L342

Awesome, I'll try and get around to this sooner rather than later :)

**Comment by LDaneliukas** [comment]
> 
> 
> Thanks for this contribution!
> It would be perfect if you could add a couple of tests to check when `enteprise_name` is set and also when there is neither `org_name` nor `enteprise_name` that it should fail.
> 
> As an example to follow, those tests should be similar to this one:
> https://github.com/Telefonica/puppet-github-actions-runner/blob/master/spec/classes/github_actions_runner_spec.rb#L317-L342

Added some tests. Still pending approval for the workflow to run. I'll add/update anything else that may be missing.

We are also working on Windows support internally, so I'd be happy to contribute that here too (separate PR ofcourse).

**Comment by mrodm** [comment]
> > Thanks for this contribution!
> > It would be perfect if you could add a couple of tests to check when `enteprise_name` is set and also when there is neither `org_name` nor `enteprise_name` that it should fail.
> > As an example to follow, those tests should be similar to this one:
> > https://github.com/Telefonica/puppet-github-actions-runner/blob/master/spec/classes/github_actions_runner_spec.rb#L317-L342
> 
> Added some tests. Still pending approval for the workflow to run. I'll add/update anything else that may be missing.

Thanks for these updates!
It has been approved the workflow to run


> We are also working on Windows support internally, so I'd be happy to contribute that here too (separate PR of course).

That would be perfect!!

**Comment by LDaneliukas** [comment]
Fixed all rubcop warnings and updated test cases to pass.

**Comment by mrodm** [comment]
> Fixed all rubcop warnings and updated test cases to pass. The "about" section of the repo should probably be updated too, since it states that the runners can be provisioned only on Debian and we are currently running on CentOS without any issues.

Good catch! we'll review and update the about section after this PR is integrated.
Glad to hear that this module is also working on CentOs hosts without any issues ! 

Thanks for this contribution!  We'll merge and release a new version soon

**Review by mrodm — APPROVED** [review]

**Pull request merged**
